services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: node_app
    ports:
      - "3003:3000"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data: