services:
  web:
    build: ./app
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - backend

  worker:
    build: ./app
    container_name: celery_worker
    depends_on:
      - redis
    command: celery -A app worker --loglevel=info
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend: