services:
  db:
    image: mysql:8.0
    container_name: mysql_volume
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3309:3306"
    volumes:
      - mydata:/var/lib/mysql

volumes:
  mydata: